### ISSUE TITLE
c_src not built when used in a rebar3 project

### ISSUE THREAD

**Issue by aseigo** [msantos/inert#2]
As with the procket library, the rebar2 based compilation does not work when used within a rebar3 application as the c_src does not get built. 

A possible solution would be to add similar Makefiles to inert as is in procket master.

**Comment by msantos** [comment]
@aseigo thanks for letting me know! I will update inert to use rebar3.

**Comment by aseigo** [comment]
Fantastic; thanks in advance!

**Comment by msantos** [comment]
Should be fixed now. If you run into any problems, please let me know!

**Comment by aseigo** [comment]
Works a charm! Thanks for the fantastically quick turn around...
