### ISSUE TITLE
Tag a release and publish to hex.pm

### ISSUE THREAD

**Issue by Vagabond** [msantos/inert#4]
Hey, thanks again for inert. it's super handy. We've been using it over in https://github.com/helium/erlang-libp2p and it'd be great to have a tag we can point at.

Additionally, we'd like to publish libp2p to hex.pm but that requires all the dependencies to be listed on hex as well. Would you consider publishing to hex, or I can publish on your behalf (and add you as an owner of the package).

**Comment by msantos** [comment]
Done!

https://hex.pm/packages/inert

Very happy to hear inert was useful to you! I read your article recently on helium's use of proof of work for radios and it was super exciting, like some technology from the future. It'll be fun reading through the code.
